export const PALETTES = {
  wool: [
    [221, 221, 221, "minecraft:white_wool", "白色の羊毛"],
    [219, 125, 62, "minecraft:orange_wool", "橙色の羊毛"],
    [179, 80, 188, "minecraft:magenta_wool", "赤紫色の羊毛"],
    [107, 138, 201, "minecraft:light_blue_wool", "空色の羊毛"],
    [177, 166, 39, "minecraft:yellow_wool", "黄色の羊毛"],
    [65, 174, 56, "minecraft:lime_wool", "黄緑色の羊毛"],
    [208, 132, 153, "minecraft:pink_wool", "桃色の羊毛"],
    [64, 64, 64, "minecraft:gray_wool", "灰色の羊毛"],
    [154, 161, 161, "minecraft:light_gray_wool", "薄灰色の羊毛"],
    [46, 110, 137, "minecraft:cyan_wool", "青緑色の羊毛"],
    [126, 61, 181, "minecraft:purple_wool", "紫色の羊毛"],
    [46, 56, 141, "minecraft:blue_wool", "青色の羊毛"],
    [79, 50, 31, "minecraft:brown_wool", "茶色の羊毛"],
    [53, 70, 27, "minecraft:green_wool", "緑色の羊毛"],
    [150, 52, 48, "minecraft:red_wool", "赤色の羊毛"],
    [25, 22, 22, "minecraft:black_wool", "黒色の羊毛"],
  ],
  concrete: [
    [207, 213, 214, "minecraft:white_concrete", "白色のコンクリート"],
    [224, 97, 1, "minecraft:orange_concrete", "橙色のコンクリート"],
    [169, 48, 159, "minecraft:magenta_concrete", "赤紫色のコンクリート"],
    [35, 137, 199, "minecraft:light_blue_concrete", "空色のコンクリート"],
    [240, 175, 21, "minecraft:yellow_concrete", "黄色のコンクリート"],
    [94, 168, 24, "minecraft:lime_concrete", "黄緑色のコンクリート"],
    [214, 101, 143, "minecraft:pink_concrete", "桃色のコンクリート"],
    [55, 58, 62, "minecraft:gray_concrete", "灰色のコンクリート"],
    [125, 125, 115, "minecraft:light_gray_concrete", "薄灰色のコンクリート"],
    [21, 119, 136, "minecraft:cyan_concrete", "青緑色のコンクリート"],
    [100, 31, 156, "minecraft:purple_concrete", "紫色のコンクリート"],
    [44, 46, 143, "minecraft:blue_concrete", "青色のコンクリート"],
    [96, 60, 32, "minecraft:brown_concrete", "茶色のコンクリート"],
    [73, 91, 36, "minecraft:green_concrete", "緑色のコンクリート"],
    [142, 32, 32, "minecraft:red_concrete", "赤色のコンクリート"],
    [8, 10, 15, "minecraft:black_concrete", "黒色のコンクリート"],
  ],
  terracotta: [
    [209, 178, 161, "minecraft:white_terracotta", "白色のテラコッタ"],
    [161, 83, 37, "minecraft:orange_terracotta", "橙色のテラコッタ"],
    [149, 88, 108, "minecraft:magenta_terracotta", "赤紫色のテラコッタ"],
    [113, 108, 137, "minecraft:light_blue_terracotta", "空色のテラコッタ"],
    [186, 133, 35, "minecraft:yellow_terracotta", "黄色のテラコッタ"],
    [103, 117, 52, "minecraft:lime_terracotta", "黄緑色のテラコッタ"],
    [160, 77, 78, "minecraft:pink_terracotta", "桃色のテラコッタ"],
    [57, 42, 36, "minecraft:gray_terracotta", "灰色のテラコッタ"],
    [135, 106, 97, "minecraft:light_gray_terracotta", "薄灰色のテラコッタ"],
    [86, 91, 91, "minecraft:cyan_terracotta", "青緑色のテラコッタ"],
    [118, 70, 86, "minecraft:purple_terracotta", "紫色のテラコッタ"],
    [74, 59, 91, "minecraft:blue_terracotta", "青色のテラコッタ"],
    [77, 51, 36, "minecraft:brown_terracotta", "茶色のテラコッタ"],
    [76, 83, 42, "minecraft:green_terracotta", "緑色のテラコッタ"],
    [143, 61, 47, "minecraft:red_terracotta", "赤色のテラコッタ"],
    [37, 23, 16, "minecraft:black_terracotta", "黒色のテラコッタ"],
  ],

  map_nature: [
    [127, 178, 56, "minecraft:grass_block", "【自然】草ブロック"],
    [247, 233, 163, "minecraft:sand", "【自然】砂"],
    [164, 168, 184, "minecraft:clay", "【自然】粘土"],
    [151, 109, 77, "minecraft:dirt", "【自然】土"],
    [255, 255, 255, "minecraft:snow_block", "【自然】雪"],
    [0, 124, 0, "minecraft:oak_leaves", "【自然】葉（緑）"],
    [129, 86, 49, "minecraft:podzol", "【自然】ポドゾル"],
  ],
  map_wood: [
    [143, 119, 72, "minecraft:oak_planks", "【木材】オークの板材"],
    [151, 91, 54, "minecraft:spruce_planks", "【木材】マツの板材"],
    [195, 179, 123, "minecraft:birch_planks", "【木材】シラカバの板材"],
    [146, 100, 77, "minecraft:jungle_planks", "【木材】ジャングルの板材"],
    [125, 85, 54, "minecraft:acacia_planks", "【木材】アカシアの板材"],
    [100, 76, 51, "minecraft:dark_oak_planks", "【木材】ダークオークの板材"],
  ],
  map_minerals: [
    [167, 167, 167, "minecraft:iron_block", "【鉱物】鉄ブロック"],
    [250, 238, 77, "minecraft:gold_block", "【鉱物】金ブロック"],
    [92, 219, 213, "minecraft:diamond_block", "【鉱物】ダイヤブロック"],
    [74, 128, 255, "minecraft:lapis_block", "【鉱物】ラピスラズリブロック"],
    [0, 217, 58, "minecraft:emerald_block", "【鉱物】エメラルドブロック"],
    [216, 175, 147, "minecraft:raw_iron_block", "【鉱物】原鉄ブロック"],
  ],
  map_building: [
    [112, 112, 112, "minecraft:stone", "【建材】石"],
    [180, 180, 180, "minecraft:stone_bricks", "【建材】石レンガ"],
    [159, 82, 36, "minecraft:bricks", "【建材】レンガ"],
    [255, 252, 245, "minecraft:quartz_block", "【建材】クォーツ"],
    [100, 100, 100, "minecraft:deepslate", "【建材】ディープスレート"],
    [225, 225, 225, "minecraft:white_concrete", "【建材】白色のコンクリート"],
    [21, 21, 26, "minecraft:black_concrete", "【建材】黒色のコンクリート"],
    [51, 76, 178, "minecraft:blue_concrete", "【建材】青色のコンクリート"],
    [208, 70, 72, "minecraft:red_concrete", "【建材】赤色のコンクリート"],
  ],
  map_liquids_fire: [
    [64, 64, 255, "minecraft:water", "【液体】水"],
    [160, 160, 255, "minecraft:ice", "【液体】氷"],
    [255, 0, 0, "minecraft:lava", "【火】溶岩・炎系"],
  ],
  map_nether: [
    [112, 2, 0, "minecraft:netherrack", "【ネザー】ネザーラック"],
    [189, 48, 49, "minecraft:crimson_nylium", "【ネザー】真紅のナイリウム"],
    [58, 142, 140, "minecraft:warped_stem", "【ネザー】歪んだ幹"],
    [
      20,
      180,
      133,
      "minecraft:warped_wart_block",
      "【ネザー】歪んだワートブロック",
    ],
    [66, 3, 11, "minecraft:nether_bricks", "【ネザー】ネザーレンガ"],
    [13, 13, 13, "minecraft:basalt", "【ネザー】玄武岩"],
  ],
  map_end: [
    [247, 233, 163, "minecraft:end_stone", "【エンド】エンドストーン"],
    [39, 67, 138, "minecraft:end_portal", "【エンド】エンド系（青）"],
  ],
};

export const GRID_THEMES = {
  contrast: { thin: "#1F2937", majorOuter: "#0E7490", majorInner: "#06B6D4" },
  darkbg: { thin: "#9CA3AF", majorOuter: "#22A3C3", majorInner: "#7EDCF3" },
  lightbg: { thin: "#111827", majorOuter: "#0B7285", majorInner: "#0EC4E7" },
  blue: { thin: "#0B1F4B", majorOuter: "#1D4ED8", majorInner: "#60A5FA" },
  yellow: { thin: "#3A2D0A", majorOuter: "#B45309", majorInner: "#F59E0B" },
};

// ...（既存 PALETTES / GRID_THEMES はそのまま）...

// ==== Bedrock 固定UUID / 最小エンジンバージョン ====
export const BEDROCK_UUID_HEADER = "8f8b83e2-4f2a-4b1c-8b79-6b6b2a7e7f21";
export const BEDROCK_UUID_MODULE = "c6a5b4f1-9e0c-4a88-9f67-2a3e5c1b2d90";
export const BEDROCK_MIN_ENGINE_VERSION = [1, 20, 0];

// ==== Java → Bedrock ID 変換 ====
export const BEDROCK_ID_MAP = {
  // Wool
  "minecraft:white_wool": "white_wool",
  "minecraft:orange_wool": "orange_wool",
  "minecraft:magenta_wool": "magenta_wool",
  "minecraft:light_blue_wool": "light_blue_wool",
  "minecraft:yellow_wool": "yellow_wool",
  "minecraft:lime_wool": "lime_wool",
  "minecraft:pink_wool": "pink_wool",
  "minecraft:gray_wool": "gray_wool",
  "minecraft:light_gray_wool": "light_gray_wool",
  "minecraft:cyan_wool": "cyan_wool",
  "minecraft:purple_wool": "purple_wool",
  "minecraft:blue_wool": "blue_wool",
  "minecraft:brown_wool": "brown_wool",
  "minecraft:green_wool": "green_wool",
  "minecraft:red_wool": "red_wool",
  "minecraft:black_wool": "black_wool",
  // Concrete
  "minecraft:white_concrete": "white_concrete",
  "minecraft:orange_concrete": "orange_concrete",
  "minecraft:magenta_concrete": "magenta_concrete",
  "minecraft:light_blue_concrete": "light_blue_concrete",
  "minecraft:yellow_concrete": "yellow_concrete",
  "minecraft:lime_concrete": "lime_concrete",
  "minecraft:pink_concrete": "pink_concrete",
  "minecraft:gray_concrete": "gray_concrete",
  "minecraft:light_gray_concrete": "light_gray_concrete",
  "minecraft:cyan_concrete": "cyan_concrete",
  "minecraft:purple_concrete": "purple_concrete",
  "minecraft:blue_concrete": "blue_concrete",
  "minecraft:brown_concrete": "brown_concrete",
  "minecraft:green_concrete": "green_concrete",
  "minecraft:red_concrete": "red_concrete",
  "minecraft:black_concrete": "black_concrete",
  // Terracotta
  "minecraft:white_terracotta": "white_terracotta",
  "minecraft:orange_terracotta": "orange_terracotta",
  "minecraft:magenta_terracotta": "magenta_terracotta",
  "minecraft:light_blue_terracotta": "light_blue_terracotta",
  "minecraft:yellow_terracotta": "yellow_terracotta",
  "minecraft:lime_terracotta": "lime_terracotta",
  "minecraft:pink_terracotta": "pink_terracotta",
  "minecraft:gray_terracotta": "gray_terracotta",
  "minecraft:light_gray_terracotta": "light_gray_terracotta",
  "minecraft:cyan_terracotta": "cyan_terracotta",
  "minecraft:purple_terracotta": "purple_terracotta",
  "minecraft:blue_terracotta": "blue_terracotta",
  "minecraft:brown_terracotta": "brown_terracotta",
  "minecraft:green_terracotta": "green_terracotta",
  "minecraft:red_terracotta": "red_terracotta",
  "minecraft:black_terracotta": "black_terracotta",
};

export const DATA_VERSION = 3953; // 必要なら環境に合わせて後で更新可
